"""Frontend Streamlit OpenHousing."""

from __future__ import annotations

import os
import streamlit as st

from client import OpenHousingAPIError, OpenHousingClient

# ==========================================================
# CONFIGURATION
# ==========================================================

DEFAULT_API_URL = "https://openhousing-api.onrender.com"

st.set_page_config(
    page_title="OpenHousing",
    page_icon="🏡",
    layout="wide",
)

# ==========================================================
# STYLE
# ==========================================================

st.markdown(
    """
<style>

.block-container{
    max-width:1200px;
    padding-top:1rem;
}

.hero{
    background:linear-gradient(135deg,#0f766e,#14b8a6);
    color:white;
    padding:2rem;
    border-radius:18px;
    text-align:center;
    margin-bottom:2rem;
}

.prediction-card{
    background:linear-gradient(135deg,#0f766e,#14b8a6);
    color:white;
    padding:2rem;
    border-radius:18px;
    text-align:center;
    margin-top:15px;
}

[data-testid="stMetric"]{
    background:#f8fafc;
    border:1px solid #e5e7eb;
    padding:15px;
    border-radius:12px;
}

</style>
""",
    unsafe_allow_html=True,
)

# ==========================================================
# HEADER
# ==========================================================

st.markdown(
    """
<div class="hero">
    <h1>🏡 OpenHousing</h1>
    <h3>AI-Powered Real Estate Valuation</h3>
    <p>
        Enter a property's characteristics and instantly receive an estimated market value
        generated by a Machine Learning model.
    </p>
    <p>
        🍅 Presented by Team Tomato
    </p>
</div>
""",
    unsafe_allow_html=True,
)

# ==========================================================
# API
# ==========================================================

api_url = os.getenv("OPENHOUSING_API_URL", DEFAULT_API_URL)
client = OpenHousingClient(api_url)

# ==========================================================
# INDICATOR
# ==========================================================

st.metric("Features Analyzed", "12")

# ==========================================================
# EXPLANATIONS
# ==========================================================

with st.expander("📚 Understanding the features used by the model"):

    st.markdown(
        """
### 🏠 Property Characteristics

- **Average Number of Rooms**: Average size of residential properties.
- **Older Homes (%)**: Share of homes built before 1940.
- **Property Tax Rate**: Local real estate taxation level.
- **Pupil-Teacher Ratio**: Indirect indicator of school quality.

### 🌆 Neighborhood Characteristics

- **Crime Rate**: General safety level of the area.
- **Low-Density Residential Areas (%)**: Share of large residential lots.
- **Industrial Land Usage (%)**: Presence of industrial and commercial activities.
- **Air Pollution Level (NOx)**: Air pollution indicator.
- **Low-Income Population (%)**: Socioeconomic indicator of the neighborhood.
- **Charles River Proximity**: Indicates whether the property borders the Charles River.

### 🚗 Accessibility

- **Distance to Employment Centers**: Proximity to major business hubs.
- **Highway Accessibility**: Ease of access to major road networks.
"""
    )

# ==========================================================
# SIDEBAR
# ==========================================================

with st.sidebar:

    st.header("⚙️ Service Monitoring")

    if st.button(
        "🔍 Check API",
        use_container_width=True
    ):

        with st.spinner("Connecting to API..."):

            try:

                health = client.health()

                if health.get("status") == "healthy":
                    st.success("API Available ✅")
                else:
                    st.warning(
                        f"Status received: {health.get('status')}"
                    )

            except OpenHousingAPIError as exc:
                st.error(str(exc))

# ==========================================================
# INPUT FORM
# ==========================================================

st.subheader("📝 Property Information")

with st.form("prediction_form"):

    tab1, tab2, tab3 = st.tabs(
        [
            "🏠 Property",
            "🌆 Neighborhood",
            "🚗 Accessibility",
        ]
    )

    # ======================================================
    # PROPERTY
    # ======================================================

    with tab1:

        col_a, col_b = st.columns(2)

        with col_a:

            rm = st.slider(
                "🛋️ Average Number of Rooms",
                1.0,
                10.0,
                6.575,
                help="Average number of rooms per dwelling.",
            )

            age = st.slider(
                "🏚️ Older Homes (%)",
                0.0,
                100.0,
                65.2,
                help="Percentage of homes built before 1940.",
            )

        with col_b:

            tax = st.number_input(
                "💰 Property Tax Rate",
                value=296.0,
                help="Property tax rate applied to residential properties.",
            )

            ptratio = st.number_input(
                "🎓 Pupil-Teacher Ratio",
                value=15.3,
                help="Indirect indicator of local school quality.",
            )

    # ======================================================
    # NEIGHBORHOOD
    # ======================================================

    with tab2:

        col_a, col_b = st.columns(2)

        with col_a:

            crim = st.number_input(
                "🚨 Crime Rate",
                value=0.00632,
                format="%.5f",
                help="Per-capita crime rate in the city.",
            )

            nox = st.slider(
                "🌫️ Air Pollution Level (NOx)",
                0.0,
                1.0,
                0.538,
                help="Nitrogen oxide concentration indicator.",
            )

            lstat = st.slider(
                "📉 Low-Income Population (%)",
                0.0,
                100.0,
                4.98,
                help="Percentage of lower socioeconomic population.",
            )

        with col_b:

            zn = st.slider(
                "🏘️ Low-Density Residential Areas (%)",
                0.0,
                100.0,
                18.0,
                help="Share of residential land zoned for large lots.",
            )

            indus = st.slider(
                "🏭 Industrial Land Usage (%)",
                0.0,
                30.0,
                2.31,
                help="Proportion of industrial and commercial land.",
            )

            chas = st.selectbox(
                "🌊 Charles River Proximity",
                (0, 1),
                format_func=lambda x: "Yes" if x else "No",
                help="Whether the area borders the Charles River.",
            )

    # ======================================================
    # ACCESSIBILITY
    # ======================================================

    with tab3:

        col_a, col_b = st.columns(2)

        with col_a:

            dis = st.number_input(
                "🚉 Distance to Employment Centers",
                value=4.09,
                help="Weighted distance to major employment centers.",
            )

        with col_b:

            rad = st.number_input(
                "🛣️ Highway Accessibility",
                min_value=1,
                value=1,
                help="Accessibility index to major highways.",
            )

    submitted = st.form_submit_button(
        "🚀 Estimate Price",
        use_container_width=True,
        type="primary",
    )

# ==========================================================
# PAYLOAD
# ==========================================================

payload = {
    "crim": crim,
    "zn": zn,
    "indus": indus,
    "chas": chas,
    "nox": nox,
    "rm": rm,
    "age": age,
    "dis": dis,
    "rad": rad,
    "tax": tax,
    "ptratio": ptratio,
    "lstat": lstat,
}

# ==========================================================
# PREDICTION
# ==========================================================

if submitted:

    with st.spinner("Calculating estimate..."):

        try:

            prediction = client.predict(payload)

            price = float(
                prediction["estimated_price_usd"]
            )

            st.success("Estimate generated successfully ✅")

            st.markdown(
                f"""
                <div class="prediction-card">
                    <h2>Estimated Price</h2>
                    <h1>${price:,.0f}</h1>
                </div>
                """,
                unsafe_allow_html=True,
            )

            with st.expander("📊 Technical Details"):

                left, right = st.columns(2)

                with left:
                    st.subheader("Request Payload")
                    st.json(payload)

                with right:
                    st.subheader("API Response")
                    st.json(prediction)

        except OpenHousingAPIError as exc:

            st.error(str(exc))